name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers only on tags like v1.0.0, v1.2.3

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ pypi-AgEIcHlwaS5vcmcCJDk4MDAzYzRjLWQ1YTctNDI3My04YzBmLWZiOWQ3MWU0ZTA5NwACKlszLCJiOTI5NjY3OC0wNmVmLTRhMWEtOGVjNC02NzhkMjk2ODZjMTEiXQAABiBh2ICEZot-Qvccby15vdbP5GKVqGTxCz9xNc_tWG-PCw }}
